### ISSUE TITLE
Oterlu API is shutting down 

### ISSUE THREAD

**Issue by SteveBox0** [shloakvatsyayan/DiscordBot#3]
Oterlu has been acquired by Reddit and as such is shutting down its API. What are your plans? Do you plan to find an alternative or remove this feature?

https://www.redditinc.com/blog/oterlu-team-joins-reddit-to-accelerate-safety-efforts

**Comment by shloakvatsyayan** [comment]
Funny how I saw this 2 years later... I just start looking back at this project for a new server I have. I am aware of this and have made plans to remove all implementations of oterlu. The original idea back in 2022 was to use GPT-3 but since GPT has gotten very poplar and GPT-4 has release so I may just use GPT-4 Turbo.
